language: go
go_import_path: github.com/tangerine-network/tangerine-consensus
os: linux
dist: trusty
sudo: required
go: 1.11.x
addons:
  apt:
    packages:
    - openssl
    - libssl-dev
    - libgmp-dev
script:
- set -e
- bin/install_tools.sh
- dep ensure -v
- make dep
- |
  if [ "${TRAVIS_PULL_REQUEST_BRANCH}" == "" ] && [ "${TRAVIS_BRANCH}" == "master" ]; then
    make test
  else
    make test-short
  fi
- make
git:
  depth: 3
cache:
  directories:
  - vendor
before_cache:
- rm -rf vendor/github.com/tangerine-network/bls
- rm -rf vendor/github.com/tangerine-network/mcl
env:
- ONLY_INTEGRATION_TEST=true NO_TEST_RACE=true
- ONLY_INTEGRATION_TEST=true
- NO_INTEGRATION_TEST=true
matrix:
  allow_failures:
  - env: ONLY_INTEGRATION_TEST=true
  fast_finish: true
  include:
  - name: Lint
    script:
    - set -e
    - bin/install_tools.sh
    - dep ensure -v
    - make dep
    - make lint
    - make vet
# notifications:
#   slack:
#     secure: "TOKEN"
